
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productdb_dev
    username: root
    password: Pallu@8982

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
